### ISSUE TITLE
Using pylightio with other python based 3D viewers

### ISSUE THREAD

**Issue by sofroniewn** [regcs/AliceLG#102]
Hello! I'm very excited about the work that has been done in this repo.

I am new to LookingGlass and I am curious about using the pylightio library to do quilt-based or live rendering with data from other python based 3D image viewers. In particular, I am a maintainer of [napari](https://github.com/napari/napari) a multidimensional image viewer from Python focused on scientific applications and I have had some users request interfacing with a looking glass display. It looks like the pylightio library and patterns used in this repo could be a great foundation, and I'm curious if you have any advice or recommendations?

If this question if not of interest of you feel free to close this issue. Thanks again for your work here.

**Comment by regcs** [comment]
Closing this, since we are already in discussion. ;)
