### ISSUE TITLE
Cannot enable in Blender 3.4.1

### ISSUE THREAD

**Issue by suciokhan** [regcs/AliceLG#109]
**Describe the bug**
When I attempt to install the plugin in Blender 3.4.1 in WIndows 11, it shows up in the add-ons but I cannot enable it.

**To Reproduce**
1. Install Blender 3.4.1
2. Download latest release here: https://github.com/regcs/AliceLG/releases/tag/v2.1.0
3. Goto edit/preferences/add-ons and click "Install..." button
4. Click the square to enable...receive error message.

**Expected behavior**
I expect there to be no error message, and AliceLG gets enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/23055812/230634338-56b49217-8e43-402c-a831-9955fa596fdd.png)

For your convenience, here is the Python in text format:
```
File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py, line 369, in enable mod.register()
File "C:\Users\fukyu\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\AliceLG\_init_.py,line 348, in reister bpy.utils.register_class(LOOKINGglASS_OT_install_dependencies)
ValueError: register_class(...): already registered as a subclass 'LOOKINGGLASS_OT_install_dependencies`
```

**Platform & Versions (please complete the following information):**
 - OS: Windows 11
 - Blender Version: 3.4.1
 - Alice/LG Version 2.1.0

**Attach log files**
[alice-lg.log](https://github.com/regcs/AliceLG/files/11179866/alice-lg.log)
[pylightio.log](https://github.com/regcs/AliceLG/files/11179868/pylightio.log)

**Comment by regcs** [comment]
@suciokhan Thank you for the report. Could you resolve the issue or is the addon still having problems on Blender 3.4.1?

**Comment by regcs** [comment]
As mentioned in our private chat, please re-open, if you encounter the issue again.
