### ISSUE TITLE
Plugin breaks rendering

### ISSUE THREAD

**Issue by EphraimB** [regcs/AliceLG#112]
**Describe the bug**
Renders in Blender are completely blank and grey. Before setting a camera in the plugin, the render works fine.

**To Reproduce**
1. Click on the arrow and looking glass
2. Set looking glass camera to the scene's camera
3. Click render quilt
4. It renders a blank

**Expected behavior**
It's supposed to render the model, for example, a cube.

**Screenshots**
<img width="1922" alt="Blender Screenshot 2023-05-14 112136" src="https://github.com/regcs/AliceLG/assets/10489639/73e4893a-f1e2-4603-a70c-ee8f7819c6b9">

**Platform & Versions (please complete the following information):**
 - OS: WIndows
 - Blender Version: 3.3 LTS
 - Alice/LG Version 2.2

**Attach log files**
Head over to Blender's addon directory ([Don't know where this is?](https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html)), in that directory go to '/AliceLG/logs/', and attach the `pylightio.log` and `alice-lg.log` here:
[alice-lg.log](https://github.com/regcs/AliceLG/files/11472273/alice-lg.log)
[pylightio.log](https://github.com/regcs/AliceLG/files/11472274/pylightio.log)

**Comment by regcs** [comment]
Hi @EphraimB, according to your screenshot, everything is correct. You need to adjust the focal plains and the clipping distances of the camera in the Looking Glass panel to enclose the part of the scene you want to render 😊

Here is a nice guide on how to get started: 

https://docs.lookingglassfactory.com/developer-tools/blender

**Comment by EphraimB** [comment]
Thank you. I got it to work but I don't think rendering does anything.

**Comment by regcs** [comment]
Did you read the complete document in the link and tried what I wrote about the focal plane and clipping settings?

**Comment by EphraimB** [comment]
I think I figured it out other than the quilt render not saving but that might be a Blender issue.

**Comment by regcs** [comment]
Alright, glad you resolved it. Closing this issue then. Please re-open, if you need any further help.
