### ISSUE TITLE
[Camera] Make the LookingGlass Camera picker animatable

### ISSUE THREAD

**Issue by regcs** [regcs/AliceLG#12]
Not sure yet, if that makes sense. But maybe it would be helpful in some situations to make this picker "animatable", that is, being able to choose different cameras in different frames for rendering. 

If anybody thinks that this is useful, please give this issue a thumbs up.

**Comment by JohJakob** [comment]
I think the easiest approach would be to get the active camera each frame. This would allow to use timeline markers with cameras bound to them. A simple “Use active camera” checkbox underneath the camera picker would then be sufficient (if checked, disable the camera picker).

**Comment by regcs** [comment]
That’s definitely a way, I did not think about yet. I will keep it in mind, thanks for the suggestion!

**Comment by regcs** [comment]
This is related to #99. The problem is: If the active camera changes based on camera markers, we need to change the clipping ranges and focal plane settings per camera.

**Comment by regcs** [comment]
Resolved by making the add-on respect camera markers, which are the Blender native way to switch cameras during an animation.
