### ISSUE TITLE
Bender 4.0: Can't find Looking Glass tab

### ISSUE THREAD

**Issue by michaelboccara** [regcs/AliceLG#125]
**Describe the bug**
I installed the AliceLG add-on in my new Blender 4.0, and I can't find the Looking Glass tab anywhere.
The add-on quick instructions is talking about View3D->LookingGlass menu but it doesn't exist

**To Reproduce**
1. Install Blender 4.0
2. Install AliceGL add-on zip provided in GitHub
3. Look for LookingGlass menu
4. Can't find

**Expected behavior**
Looking Glass tab visible

**Screenshots**
![image](https://github.com/regcs/AliceLG/assets/5111204/ae5088f4-b386-4c85-bbc8-541423e9940e)
![image](https://github.com/regcs/AliceLG/assets/5111204/e061b517-e1c0-4755-abe3-c7f1acdc1a7b)

**Platform & Versions (please complete the following information):**
 - OS: Windows 11
 - Blender Version: 4.0
 - Alice/LG Version 2.2.0

**Attach log files**
[alice-lg.log](https://github.com/regcs/AliceLG/files/13536893/alice-lg.log)
[pylightio.log](https://github.com/regcs/AliceLG/files/13536894/pylightio.log)
[side-packages-install.log](https://github.com/regcs/AliceLG/files/13536895/side-packages-install.log)

**Comment by paperdev-code** [comment]
![image](https://github.com/regcs/AliceLG/assets/51487819/14f35ba9-fc35-4616-9ef1-1ff55c5ca586)
It's over here for me.

**Comment by regcs** [comment]
@michaelboccara: Did the comment of @paperdev-code help you or are you still having issues?

**Comment by Bud-Stoner** [comment]
I struggled with this same issue for days, before finally figuring it out. the tab was coming up hidden...

![20231208_092654](https://github.com/regcs/AliceLG/assets/153304302/aee539cf-1071-4fc6-94f4-e6df0705234e)

notice the arrow in my picture, it points to a tiny arrow that you can use to pull out the tabs as seen in the pic above from @paperdev-code.

**Comment by michaelboccara** [comment]
> @michaelboccara: Did the comment of @paperdev-code help you or are you still having issues?

Yep!
It did... Now I'm trying to work this out and get to see something deep in my LKG, but hopefully I will sort this out, or open a new issue if I don't.
Closing this for now
