### ISSUE TITLE
[Lightfield Window] Speed up offscreen rendering in Blender

### ISSUE THREAD

**Issue by alxdncn** [regcs/AliceLG#20]
Currently in Blender 2.8 and 2.9, offscreen rendering is much slower than in Blender 2.79. We want to improve this as much as possible.

See here for more details: https://developer.blender.org/T89204

**Comment by regcs** [comment]
Brecht tried to mitigate the issue [with a patch](https://developer.blender.org/rBd03b26edbdc3a9fe87fde44bd8db8c4a67a36757) improve the offscreen rendering speed by a viewport caching, which introduced other bugs and therefore did not make it into master.

**Comment by regcs** [comment]
Some analysis of the cause for the issue introduced by Brecht's patch:
https://developer.blender.org/T89204#1182799

**Comment by regcs** [comment]
@GottfriedHofmann created post on devtalk.blender.org to discuss the issue with the community:
https://devtalk.blender.org/t/viewport-cache-redraw-when-rotating-and-panning-but-not-when-using-the-mouse-wheel/20344

**Comment by alxdncn** [comment]
Worth investigating, while we wait to see how to fix the view port drawing issues on Brecht's patch, using the preview mode to get additional performance improvements.

**Comment by regcs** [comment]
Successfully fixed the initial patch by Blender core developer Brecht:
https://developer.blender.org/D13235

The patch is accepted in will soon land in Blender 3.0+. Offscreen rendering now caches framebuffers and textures in Blender, which decreases repeated offscreen rendering times by approximately 30 to 50%. That probably is as good as we can get for now. But it should get us close to 10 fps for the addon's live view.
