### ISSUE TITLE
Add multiview renderer option to camera

### ISSUE THREAD

**Issue by alxdncn** [regcs/AliceLG#23]
We want to add an additional modality to the camera that leverages Blender's built-in multiview rendering system.

**Comment by regcs** [comment]
During refactoring of the render operator I implemented some very basic code parts to create the multiview cameras just before rendering a frame and deleting them afterwards. However, this still lacks a lot of functionality and requires further work (57ea1fd322bc85654152f0e8f488d48323b0ffcf).

**Comment by regcs** [comment]
Added an option in the preference pane to choose between "Single Camera" and "Multiview Camera" (1da0828aad006de4b81ebdefb4abaeae4ccb8f4b). In both modes, the cameras for the required rendering perspectives are created and deleted dynamically, view files are written to disk, and a quilt is assembled (f0e4a3eb372bfc388d66d5cc5d6f5cb54de82286).
