### ISSUE TITLE
Add detailed logger mechanism

### ISSUE THREAD

**Issue by regcs** [regcs/AliceLG#24]
Instead of printing everything to the console, create log files. This has already been started with a45164f985b72255f80af799f85ff8a746b5c89f but needs to be implemented in all areas of the code base and will be done during the refactoring for version 2.0.

**Comment by regcs** [comment]
What information do we want to log? By default, I guess, the log should only include warnings, errors, and unhandled exception. But probably it would be good to have an option in the add-on preferences that can be toggled to add additional  debugging information to the log file, so the user can turn this on upon request. 

**Unhandled exceptions:** 
In order to get unhandled exceptions into our log file, [we need to overwrite the "sys.excepthook(type, value, traceback)"](https://stackoverflow.com/questions/6234405/logging-uncaught-exceptions-in-python).

**Comment by alxdncn** [comment]
I would also display details on status of the connection to HoloPlay Service, but aside from that, warnings, errors, and unhandled exceptions sounds appropriate.

In terms of toggling additional debugging information, I defer to you and @GottfriedHofmann what would be useful for a developer as you have more experience with Blender than I.

**Comment by regcs** [comment]
The basic mechanism is now implemented and all existing "print()" calls were exchanged. Furthermore, unhandled exceptions are written to the log file for debugging purposes. What is left to do is the preference toggle button, which allows to turn on/off detailed logging. At the moment all details are written.
