### ISSUE TITLE
"No Looking Glass Found" but other programs see it

### ISSUE THREAD

**Issue by omgitsraven** [regcs/AliceLG#26]
I'm running Blender 2.92 on Windows 10; HoloPlay Service can see my Looking Glass Portrait, and HoloPlayStudio can display content on it fine. I initially tried the "official" Looking Glass blender plugin, and it worked, but I found it awkward to use, so the people in the Looking Glass discord recommended I try this one instead... However, after installing it and relaunching Blender, the first dropdown in the side panel just says "No Looking Glass Found", even after I click the 'reload' button. (I unchecked the official plugin in the add-ons menu before installing this one.)

**Comment by regcs** [comment]
There are two things you can check/provide so that we can find the issue:

1. Which version of the add-on are you using?
2. Did you install the Python packages from the add-on's preference pane?
3. Could you [start Blender in command line mode](https://docs.blender.org/manual/en/latest/advanced/command_line/launch/windows.html) and post the console output here?

**Comment by omgitsraven** [comment]
1. the latest version, 1.1.5-beta
2. Yes
3.
```
Read prefs: C:\Users\Hazel\AppData\Roaming\Blender Foundation\Blender\2.92\config\userpref.blend
Initializing add-on  Alice/LG-beta v1.1.5
 # Add-on path is: C:\Users\Hazel\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\AliceLG-beta7
Initializing Holo Play Core:
 # Registering at Holoplay Service as: Alice/LG-beta v1.1.5
 # HoloPlay Service version: None
 # HoloPlay Core SDK version: 1.0.0
 # Number of connected displays: 0
########################################################################
Initialized the Looking Glass Addon.
Saved session recovery to 'C:\Users\Hazel\AppData\Local\Temp\quit.blend'

Blender quit
```

**Comment by regcs** [comment]
Thanks for the info. So, for some reason, the add-on can't find the packages that should be installed. Could you check in the preference pane again, if the "install" button is still there? If so, please try the following:

1. Close Blender.
2. Go to C:\Users\Hazel\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\AliceLG-beta7\lib and post the content of the "install.log" file here.

**Comment by omgitsraven** [comment]
I'm sorry, I'd completely missed that the add-on has its own 'install' button separate from Blender's. I looked at the installation instructions in the readme but they just looked like the usual add-on installation process so my eyes glazed over the rest... I've clicked the second 'install' button and it works perfectly now, thank you.

It might be worth having something that blanks out the tab with a "PLEASE GO BACK AND CLICK INSTALL" message if someone makes the same mistake I did, but if I'm the first person to mess that up then never mind :) Sorry!

**Comment by regcs** [comment]
Thanks, I will keep that in mind for the version 2.0 we are currently working on.
