### ISSUE TITLE
Feature request: override "depth of field distance" with "focal plane" value

### ISSUE THREAD

**Issue by omgitsraven** [regcs/AliceLG#29]
I just tried adapting a shot from an existing scene to render a quilt, but the results were coming out very blurred, even though I had the Looking Glass "focal plane" value set exactly where it should be...  It took me a moment to realise that the camera also had "depth of field" enabled, and its distance value was still set to something very different from the looking glass "focal plane" value.

Now that I know to do so, it's admittedly not *too* hard to just copy the value from the "focal plane" field to the "distance" field before rendering, but it would be handy if the "distance" field could automatically be set to match the focal plane when rendering.

**Comment by regcs** [comment]
Thanks for the suggestion. Should be easy to implement, I am just not totally sure if this is something that should be automated by default or as a toggable option.

**Comment by regcs** [comment]
Implemented in Alice/LG 2.2.
