### ISSUE TITLE
Aborting with ESC does not work

### ISSUE THREAD

**Issue by GottfriedHofmann** [regcs/AliceLG#33]
When rendering a single frame or animation, there is no way to abort the rendering process other than closing Blender.

Tested on Windows 10 with Blender 2.93 with 19b844591867725ec18aeb15fd5e5b5a67579dd4 and https://github.com/regcs/AliceLG/pull/32/commits/489ac10ce251018adccac631de989fedada88021 .

See 0:30 onwards in this screencast: https://www.dropbox.com/s/2jr2grmpnrrx0l5/aliceLG_quiltsuffix_render_anim_view_cleanup.mp4?dl=0

**Comment by regcs** [comment]
It seems, our issue might be connected to this unresolved issue in Blender:

https://developer.blender.org/T52258

The complete_render() handler (and probably the cancel_render() handler as well) is called before the `bpy.ops.render.render` operator ends. Therefore, the operator is called multiple times, which results in multiple failed render starts. If the timing is bad, this might result in the observed behavior.

Trying to work around this now according to the following post:

https://blender.stackexchange.com/questions/143719/automated-rendering-actions-in-modal-operator-is-cancelled

**Comment by regcs** [comment]
**Note:** 
For upcoming Alice/LG 2.0 I now added a button next to the progress bar, which appears during quilt rendering. Maybe this will work more reliably.

**Comment by regcs** [comment]
@GottfriedHofmann or @alxdncn Could you test if the new button works for aborting?

**Comment by alxdncn** [comment]
I tested this on release 2.0.1-beta and was able to abort using both the UI button and the escape key.

**Comment by GottfriedHofmann** [comment]
Testet it as well and it works with both the button and the esc key.

**Comment by regcs** [comment]
Excellent! Thanks for testing this out!
