### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by omgitsraven** [regcs/AliceLG#36]
Are there instructions somewhere on how to produce a build of the latest commit, in between official releases?

**Comment by regcs** [comment]
The easiest way should be the following:
1. Go to the repository main page.
2. Click on green "Code" button.
3. In the drop-down click on "Download .zip"
4. Use this lib to install the add-on as usual in Blender.
5. Don't forget to click on the "install" button in the preferences of the add-on.

**Comment by omgitsraven** [comment]
That worked, thank you!
