### ISSUE TITLE
Feature request: automatically close Looking Glass window when it's the last window open

### ISSUE THREAD

**Issue by omgitsraven** [regcs/AliceLG#41]
No matter how many times I remind myself, somehow I nearly always wind up forgetting to close the Blender window open on my Looking Glass when I'm done in Blender; I just alt-F4 the window on my desktop, and go on with my day, forgetting that Blender is still running because that one last window is still open.

**Comment by regcs** [comment]
This won't make it into Alice/LG v. 1.x anymore, but will be solved due to another live view mechanism with the currently ongoing refactoring for Alice/LG v.2.0. So, I consider this request fulfilled.
