### ISSUE TITLE
[Rendering] Implement render farm support

### ISSUE THREAD

**Issue by regcs** [regcs/AliceLG#45]
Currently, rendering quilts on a render farm seems not to work. We need to look into that.

**Comment by regcs** [comment]
**Note for later:**

The user reporting the issue has mentioned that the render operator must be called in blocking mode. There are actually two operators that are called in the add-on:
1. Our operator which handles the render pipeline.
2. The `bpy.ops.render.render` operator.

An approach to solve the problem might, thus, be connected to the following approaches:
1. Set the attribute 'BLOCKING' for our own operator.
2. Internally call `bpy.ops.render.render()` instead of `bpy.ops.render.render("INVOKE_DEFAULT")` because the latter is running the operator in modal mode.

Since we need a non-blocking operation for normal usage of the add-on, the best approach would be to create a second blocking operator, which can be called from scripts by users who want to render on a render farm.

**Comment by alxdncn** [comment]
This would be fixed with multi-view rendering, which we're currently implementing as an option, though we'll need to test to ensure that's the case.

We can also attempt to fix this for single-view rendering.

**Comment by regcs** [comment]
After talking to another render farm user, I am getting the impression that this can be solved by implementing the above mentioned second operator and instead of processing everything in a modal loop, just use a normal loop within the operators "invoke()" call. This operator would be blocking and can be called from command line.

**Comment by regcs** [comment]
I did some research on render farms today and it seems every render farm works a bit different. That means, the only thing we can do on the add-on side is to provide a mechanism that enables render farms to add support for Alice/LG. There are three things I would implement:

1. A dedicated `render.quilt_blocking()` operator that can be called from python scripts to start the quilt rendering process in a blocking manner.
2. Two command line arguments `--alicelg-render` and `--alicelg-render-anim` that Alice/LG will check for on start up. If Blender is called with these arguments, Alice/LG will automatically call the new `render.quilt_blocking()` operator to start the render process. 

Does that sound reasonable to you?

**Comment by regcs** [comment]
408e74d3245a27694a8a5c04375cec1f319eb306 adds command-line arguments `-alicelg-render` and `-alicelg-render-anim`, which start a quilt rendering or quilt animation rendering when calling Blender in background mode from the command line. These can be called by render farms. Either of the both arguments must be called after all Blender arguments, i.e. following a `--`. For example:

`blender -b BLENDFILE_PATH -- -alicelg-render`

This will render out the quilt for the BLENDFILE_PATH and will use the settings saved in this `.blend` file. Still need to implement a bit of refinement (e.g., What if the user / renderfarm also passes an output path for the file?
