### ISSUE TITLE
[Linux] Lightfield viewport opens in wrong window on Linux

### ISSUE THREAD

**Issue by regcs** [regcs/AliceLG#5]
Probably some timing issue with xdotools, which does not see the correct active window.

**Comment by lonetech** [comment]
Yes. It is a weak hack in the first place; even if the window was the most recently opened, that doesn't necessarily make it active. I should go chat with some BF-committers to see if we can get positioning into the API.

**Comment by regcs** [comment]
Yeah, its a pity that your suggested modification of the window_new operator hasn't been reviewed yet. Would be great to see it in Blender. Using xdotool and with some help of another LG user on discord we already managed to identify the new window 's ID on linux. But it still does weird things on his system ...

**Comment by regcs** [comment]
The current live view functionality will be removed and therefore this doesn't need to be fixed anymore.
