### ISSUE TITLE
[Rendering] Animation Render Quilt Stitches only from 1st frame of range

### ISSUE THREAD

**Issue by joemagiv** [regcs/AliceLG#58]
1. Set up an animation
2. Select a range of frames for the animation
3. Render the animation quilt with Alice
Bug --> The output is only the first frame repeated, views are rendered correctly but when the stitched together quilt is created it is only using views from the first frame of the animation range.

**Comment by regcs** [comment]
Thanks for the report. Did this happen with Alice/LG 2.0.1 as well?

**Comment by regcs** [comment]
@joemagiv I already posted on Discord, but just want to double-check here: Has the issue been resolved for you?

**Comment by regcs** [comment]
Closing this for now. If anybody encounters this issue again, please reopen.

**Comment by regcs** [comment]
Should be fixed by 51a25e332eb1b7b5b1d1900ad1b5994209d69d82.
