### ISSUE TITLE
Install : Traceback Error when trying to enable the add-on by activating the check box on the left

### ISSUE THREAD

**Issue by Aymeric000** [regcs/AliceLG#60]
Hi Christian ;)

It fails to enable the add-on : Traceback Error when trying to enable the add-on by activating the check box on the left

LOG :
Report: Error
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'AliceLG-alice-lg-2'

CONFIG :
MacOS Big Sur 11.4 
Blender 2.93.3
Holoplay Service 1.2.2

Thanks in advance for your help
Aymeric

**Comment by regcs** [comment]
Hi Aymeric,

seems like you downloaded the wrong file. Could you try to download the "AliceLG-2.0.2-beta.zip" on the release page here: https://github.com/regcs/AliceLG/releases/tag/v2.0.2-beta

Then try to install again and let me know if it works.

**Comment by Aymeric000** [comment]
Hi Christian 

The installation worked well. Thansk you very much !
now let’s try :))

Aymeric

**Comment by regcs** [comment]
Great, have fun! :)
