### ISSUE TITLE
[Rendering] Rendering fails on Network Drives.

### ISSUE THREAD

**Issue by bryanlyon** [regcs/AliceLG#71]
When rendering a single frame or an animation to a network drive, it fails after rendering the last view before it makes the quilt..   In the case of an animation it fails on the first frame.  

Logs show an error of

Python: 
location: <unknown location>:-1

and all rendering stops, however, AliceLG does not stop its attempts but also doesn't move on, instead just freezing with the last view render displayed.

I believe it's from a failure in reading the separate view files in to create the quilt.

**Comment by regcs** [comment]
Thanks for reporting. I think, your diagnosis is correct. The question is why it fails reading from the network drive. Could you provide the `alice-lg.log` and `pylightio.log` log-files from the `../AliceLG/logs/` folder as well? There might be several log files with a date in the name. I need those from the day, where the error occurred.

**Comment by regcs** [comment]
@bryanlyon This message is just a short reminder for you to provide the log files. :)

**Comment by bryanlyon** [comment]
Couldn't find the log file.

Here is the error traceback data:  
[CRITICAL] 12/12/2021 20:26:19 - An unhandled error occured. Here is the traceback:
Traceback (most recent call last):
  File "C:\Users\Bryan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\AliceLG\lightfield_render.py", line 1515, in modal
    if not self.render_settings.job.assemble_quilt():
  File "C:\Users\Bryan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\AliceLG\lightfield_render.py", line 506, in assemble_quilt
    shutil.copy(self.view_filepath(), self.quilt_filepath())
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\shutil.py", line 427, in copy
    copymode(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\shutil.py", line 316, in copymode
    chmod_func(dst, stat.S_IMODE(st.st_mode))
OSError: [WinError 87] The parameter is incorrect: '\\\\MiniMule\\easystore\\Blender\\Render\\Animation\\Quilt Render Result_f00_qs8x6a0.75_v47_qs8x6a0.75.png'

**Comment by regcs** [comment]
Thanks, @bryanlyon. That helps, although I have no idea why it fails yet. But I will look into it.

PS: log files of the addon are located in `%USERPROFILE%\AppData\Roaming\Blender Foundation\Blender\**_BLENDERVERSION_**\Scripts\addons\AliceLG\logs`

**Comment by regcs** [comment]
Could you do me a favor and verify two things:

1. Does the issue also occur if you render to a normal drive (no network drive)?
2. Could you uncheck the "Add Metadata" option and see if the issue persists?

**Comment by bryanlyon** [comment]
It does not happen on a normal drive (It's how I found the cause).  Metadata flag does not affect the issue.

**Comment by regcs** [comment]
Thanks for checking. I guess, I have to do some research on that one. Since the error is raised in the python library `shutil`, it is probably something specific to Blender's Python integration. The following path is correct and exists on your network drive, correct?

`\\MiniMule\easystore\Blender\Render\Animation\`

> And something seems to have prevented alicelg from writing the logs, as the only file in that folder is "__ init __.py" (without the spaces for markdown reasons)

That's another strange thing. Which version of Alice/LG are you using?

**Comment by bryanlyon** [comment]
The path works, and all the views are written there successfully.  Perhaps it's related to Blender running on Windows and the network drive is running on Linux over Samba.

v.2.0.4 on Blender 3.0

**Comment by regcs** [comment]
Ok, so when the path exists and all views are created ... do they all have the name structure:

`Quilt Render Result_f00_qs8x6a0.75_v47_qs8x6a0.75.png`

What bothers me in particular is that the file name given in the error message has two times the `qs8x6a0.75` part. I just want to exclude that the files are not found because they are simply not named or existing in the expected way.

> Perhaps it's related to Blender running on Windows and the network drive is running on Linux over Samba.

I could imagine that it is a file permission issue. I will keep in mind that the server is running on a different OS.

**Comment by regcs** [comment]
I may have a workaround. Could you test, if the following version of Alice/LG works for you?

[AliceLG.zip](https://github.com/regcs/AliceLG/files/7771138/AliceLG.zip)

**Comment by regcs** [comment]
@bryanlyon Hope you had a nice Christmas holiday and wish you a happy new year! If you would find time to test the above version, it would great. Thank you!

**Comment by regcs** [comment]
@bryanlyon Since this issue seems to be dead, I consider it fixed with the proposed commit 5df6a41. In case you still see the issue, please re-open. ;)
