### ISSUE TITLE
stuck "last render job incomplete"

### ISSUE THREAD

**Issue by starpause** [regcs/AliceLG#80]
I have an error message which I can't get rid of. I've tried: 

- restarting blender
- disableing AliceLG, restarting blender, re-enabling AliceLG

![image](https://user-images.githubusercontent.com/408953/149085834-91efade9-58d1-45c1-a3eb-a97b8db4c0b8.png)

When I hit "continue" or "discard" it resets my output path and throws this error:

![image](https://user-images.githubusercontent.com/408953/149085970-93f5bcb9-6585-4063-b7a9-914665cb78aa.png)

If I set my output path again, hit either continue or discard, same thing. Using 2.0.4.

**Comment by regcs** [comment]
Usually, hitting "discard" should reset everything to normal. Could you provide me with the alice-lg.log and pylightio.log files from the addon `logs` folder? That might help me in solving the underlying issue.

As a workaround which allows you to continue with your blend-file, you can do the following:

1. Go to the addon folder
2. In the addon folder there is another folder called `tmp`
3. In there you should find a file that has the same name like
Your .blend file but with a ".lock" attached

If you delete this lock file, the message will disappear. However, if you do that you also have to start the render job all over again.

**Comment by regcs** [comment]
@starpause Since I didn't hear anything back from you, I guess the problem did not appear again? If so, I would close this issue.

**Comment by regcs** [comment]
Closed due to inactivity. Please re-open, if the issue persists.
