### ISSUE TITLE
Animation crash

### ISSUE THREAD

**Issue by Hauke12345** [regcs/AliceLG#83]
Hi,

First of all, thank you for the addon, I think it is great and I love to see my animations on the looking glass!

I have a problem with the animation. It renders about 10 frames then it either stops or blender crushes completely. 
I tried this with Blender 2.93.7 and 3.00 alpha and with cycles CPU or GPU and also with eevee. In eevee it rendered about 40 frames before it crashed. At one instance, I noticed that the Blender GUI froze and then it continued rendering for 3 more frames.

When I rendered the default scene in 2.92.7 with cycles, I get the following errors (at frame 10): 
Failed to create CUDA context (unknown error) and in the terminal:

_[Alice/LG] [CRITICAL] 01/27/2022 18:09:15 - An unhandled error occured. Here is the traceback:
Traceback (most recent call last):
  File "C:\Users\hca\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\AliceLG\lightfield_viewport.py", line 1054, in drawCameraFrustum
    batch_lines = batch_for_shader(self.frustum_shader, 'LINES', {"pos": coords_local}, indices=self.frustum_indices_lines)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy_types.py", line 724, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type LOOKINGGLASS_OT_render_frustum has been removed_

This is my first github post, let me know, if I missed some relevant information.

**Comment by Hauke12345** [comment]
Hi,
I found a workaround: to render the animation as a background process. This also renders double as fast for my scene.

**Comment by regcs** [comment]
Hi, I am glad you like the addon and thanks for reporting the bug. It seems to be related to a specific error in the camera frustum.

Could you please provide me with the `alice-lg.log` and `pylightio.log` files from the addon's `logs` folder?

> I found a workaround: to render the animation as a background process. This also renders double as fast for my scene.

Are you using Alice/LG's command line options for this?

**Comment by regcs** [comment]
Closed due to inactivity.
