### ISSUE TITLE
Blender add version 2.0.5 won't install/enable on Blender 3.0.1

### ISSUE THREAD

**Issue by gabrielhatcher** [regcs/AliceLG#85]
Platform:
Ubuntu 20

To replicate:
-download Blender 3.0.1
-install add-on from file
-when you try to enable, it throws the error:

Traceback (most recent call last):
  File "/home/username/blender-3.0.1-linux-x64/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'AliceLG-2'

Remedy:
-The 2.0.3 version of the add-on will still install for some reason.
-The exact same file for 2.0.5 works in the Blender 2.93.8 LTS

**Comment by regcs** [comment]
Hi @gabrielhatcher, sorry for the late response. Could you check in Blenders addon directory if the name of the folder is `AliceLG`. It seems like it is `AliceLG-2...`, which would be wrong.

**Comment by regcs** [comment]
Since there was no response in 2 weeks, I assume the issue is resolved.

@gabrielhatcher If you still run into problems, feel free to re-open.
