### ISSUE TITLE
Unable to install add-on. Can't get past installing python dependencies

### ISSUE THREAD

**Issue by starcraft086** [regcs/AliceLG#89]
Hi, 
I am unable to get past the install dependencies warning message on the blender add-on menu. 

I sometimes see the following error message:

<img width="654" alt="Screenshot 2022-03-13 at 19 15 16" src="https://user-images.githubusercontent.com/88210971/158075433-d351ed41-40d1-4b26-9d4f-c1d87d4b1f00.png">

I'm using macOS Monterey, M1 chip, blender version 2.93, and Alice LG 2.05.

Thanks, I appreciate your help.

**Comment by regcs** [comment]
Hi,

which exact version of Blender 2.93 are you using (2.93.x)? And please provide the log files from the addons "logs" directory!

To make it easier to help you and to spare some time for me, please follow the "Bug report" template the next time, when you submit a bug report. Thank you!

**Comment by starcraft086** [comment]
Yes, so the blender version is 2.93.8.  I haven't added any log reports because I don't have an aliceLG folder inside my addons directory.

**Comment by starcraft086** [comment]
I reinstalled Blender which produced the log file:
[alice-lg.log](https://github.com/regcs/AliceLG/files/8240921/alice-lg.log)
[side-packages-install.log](https://github.com/regcs/AliceLG/files/8240924/side-packages-install.log)
The pylightio file is empty.
Hope this makes the issue clearer.

**Comment by regcs** [comment]
Alright, thanks. One of the dependencies (`cffi`) fails to install. The reason is probably the M1 architecture - what I don't understand though is, that we didn't have issues like that before on the M1.

Could you please download Blender 3.0 and try to install Alice/LG there?

**Comment by regcs** [comment]
Could you also provide the alice-lg.log? You provided the side-packages-install.log two times.

**Comment by starcraft086** [comment]
Sorry about that. Here it is:
[alice-lg.log](https://github.com/regcs/AliceLG/files/8256225/alice-lg.log)

**Comment by regcs** [comment]
Just to be sure: Are the screenshots really taken _after_ trying the install? Because it seems to be a bit incoherent what the log tells. At least parts of the packages should be installed correctly, but there are none at all. 

Also: Did you try Blender 3.0 or Blender 3.1? Because in the last message you states 3.1 and the message before 3.0.

**Comment by regcs** [comment]
Ok, then it would be better to test Blender 3.0 on your M1 again. There are currently issues with Alice/LG not installing properly on Blender 3.1.

**Comment by regcs** [comment]
Closed due to inactivity.
